const CURRENCY = 'د.ج';

const PRODUCTS = [
  { id:1, name:'قميص رجالي كلاسيكي', price:3500, oldPrice:4500, category:'ملابس',
        image:'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&h=600&fit=crop',
                  rating:4.6, reviews:87, badge:'خصم',
                                desc:'قميص رجالي بقصّة أنيقة، مصنوع من القطن 100%، مناسب للمناسبات والعمل اليومي.' },

                                                { id:2, name:'فستان نسائي أنيق', price:6500, oldPrice:null, category:'ملابس',
                                                                    image:'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&h=600&fit=crop',
                                                                                            rating:4.8, reviews:112, badge:'جديد',
                                                                                                                        desc:'فستان نسائي عصري بتصميم راقي، مثالي للسهرات والمناسبات الخاصة.' },

                                                                                                                                                      { id:3, name:'جاكيت شتوي مبطن', price:8900, oldPrice:11000, category:'ملابس',
                                                                                                                                                                                        image:'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=600&fit=crop',
                                                                                                                                                                                                                              rating:4.7, reviews:65, badge:'خصم',
                                                                                                                                                                                                                                                                        desc:'جاكيت شتوي دافئ ومقاوم للماء، بتصميم عصري يناسب جميع الإطلالات.' },

                                                                                                                                                                                                                                                                                                                    { id:4, name:'هاتف ذكي حديث', price:45000, oldPrice:52000, category:'هواتف',
                                                                                                                                                                                                                                                                                                                                                                    image:'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&h=600&fit=crop',
                                                                                                                                                                                                                                                                                                                                                                                                                        rating:4.9, reviews:203, badge:'خصم',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                desc:'هاتف ذكي بشاشة AMOLED عالية الدقة، كاميرا 108MP، وبطارية تدوم طوال اليوم.' },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          { id:5, name:'سماعات لاسلكية', price:4500, oldPrice:null, category:'هواتف',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        image:'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&h=600&fit=crop',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          rating:4.7, reviews:145, badge:'جديد',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                desc:'سماعات بلوتوث بعزل ضجيج نشط، صوت نقي، وبطارية تدوم حتى 30 ساعة.' },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { id:6, name:'شاحن سريع 65W', price:1800, oldPrice:2400, category:'هواتف',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    image:'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&h=600&fit=crop',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    rating:4.5, reviews:98, badge:'خصم',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        desc:'شاحن سريع بقوة 65 واط، يشحن هاتفك بالكامل في أقل من ساعة.' },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              { id:7, name:'عطر رجالي فخم', price:7500, oldPrice:9500, category:'عطور',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        image:'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&h=600&fit=crop',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      rating:4.8, reviews:156, badge:'خصم',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        desc:'عطر رجالي شرقي فخم، برائحة تدوم طويلاً وتترك أثراً لا يُنسى.' },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { id:8, name:'عطر نسائي زهري', price:8200, oldPrice:null, category:'عطور',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    image:'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&h=600&fit=crop',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rating:4.9, reviews:178, badge:'جديد',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                desc:'عطر نسائي بنفحات زهرية راقية، مثالي للإطلالات اليومية والمناسبات.' },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  { id:9, name:'عطر مسك أبيض', price:5500, oldPrice:6800, category:'عطور',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        image:'https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=600&h=600&fit=crop',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  rating:4.6, reviews:124, badge:'خصم',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                desc:'عطر مسك أبيض ناعم بثبات عالٍ، مناسب للرجال والنساء.' }
const CURRENCY = 'د.ج';

function img(color, icon){
  return "data:image/svg+xml;utf8," + encodeURIComponent(
      '<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600"><rect width="600" height="600" fill="' + color + '"/><text x="300" y="330" font-size="200" text-anchor="middle" fill="white">' + icon + '</text></svg>'
        );
        }

        const PRODUCTS = [
          { id:1, name:'قميص رجالي كلاسيكي', price:3500, oldPrice:4500, category:'ملابس',
              image: img('#6D28D9','👔'),
                  rating:4.6, reviews:87, badge:'خصم',
                      desc:'قميص رجالي بقصّة أنيقة، مصنوع من القطن 100%، مناسب للمناسبات والعمل اليومي.' },

                        { id:2, name:'فستان نسائي أنيق', price:6500, oldPrice:null, category:'ملابس',
                            image: img('#C9A227','👗'),
                                rating:4.8, reviews:112, badge:'جديد',
                                    desc:'فستان نسائي عصري بتصميم راقي، مثالي للسهرات والمناسبات الخاصة.' },

                                      { id:3, name:'جاكيت شتوي مبطن', price:8900, oldPrice:11000, category:'ملابس',
                                          image: img('#1e293b','🧥'),
                                              rating:4.7, reviews:65, badge:'خصم',
                                                  desc:'جاكيت شتوي دافئ ومقاوم للماء، بتصميم عصري يناسب جميع الإطلالات.' },

                                                    { id:4, name:'هاتف ذكي حديث', price:45000, oldPrice:52000, category:'هواتف',
                                                        image: img('#2563eb','📱'),
                                                            rating:4.9, reviews:203, badge:'خصم',
                                                                desc:'هاتف ذكي بشاشة AMOLED عالية الدقة، كاميرا 108MP، وبطارية تدوم طوال اليوم.' },

                                                                  { id:5, name:'سماعات لاسلكية', price:4500, oldPrice:null, category:'هواتف',
                                                                      image: img('#059669','🎧'),
                                                                          rating:4.7, reviews:145, badge:'جديد',
                                                                              desc:'سماعات بلوتوث بعزل ضجيج نشط، صوت نقي، وبطارية تدوم حتى 30 ساعة.' },

                                                                                { id:6, name:'شاحن سريع 65W', price:1800, oldPrice:2400, category:'هواتف',
                                                                                    image: img('#dc2626','🔌'),
                                                                                        rating:4.5, reviews:98, badge:'خصم',
                                                                                            desc:'شاحن سريع بقوة 65 واط، يشحن هاتفك بالكامل في أقل من ساعة.' },

                                                                                              { id:7, name:'عطر رجالي فخم', price:7500, oldPrice:9500, category:'عطور',
                                                                                                  image: img('#7c3aed','💎'),
                                                                                                      rating:4.8, reviews:156, badge:'خصم',
                                                                                                          desc:'عطر رجالي شرقي فخم، برائحة تدوم طويلاً وتترك أثراً لا يُنسى.' },

                                                                                                            { id:8, name:'عطر نسائي زهري', price:8200, oldPrice:null, category:'عطور',
                                                                                                                image: img('#ec4899','🌸'),
                                                                                                                    rating:4.9, reviews:178, badge:'جديد',
                                                                                                                        desc:'عطر نسائي بنفحات زهرية راقية، مثالي للإطلالات اليومية والمناسبات.' },

                                                                                                                          { id:9, name:'عطر مسك أبيض', price:5500, oldPrice:6800, category:'عطور',
                                                                                                                              image: img('#f59e0b','🕌'),
                                                                                                                                  rating:4.6, reviews:124, badge:'خصم',
                                                                                                                                      desc:'عطر مسك أبيض ناعم بثبات عالٍ، مناسب للرجال والنساء.' }
                                                                                                                                      ];